name: taskman

services:
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - taskman_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  taskman_data:
